import type { NpcStatBlock } from "@/lib/table/types";
import { emptyNpc } from "@/lib/table/types";

export type BestiaryEntry = {
  id: string;
  category: "minion" | "skirmisher" | "brute" | "elite" | "boss" | "npc";
  template: Omit<NpcStatBlock, "id">;
};

export const BESTIARY: BestiaryEntry[] = [
  {
    id: "guard",
    category: "minion",
    template: {
      name: "Guard",
      cr: "1/8",
      ac: 16,
      hp: 11,
      maxHp: 11,
      speed: "30 ft.",
      abilities: { str: 13, dex: 12, con: 12, int: 10, wis: 11, cha: 10 },
      attacks: [{ name: "Spear", bonus: 3, damage: "1d6+1" }],
      traits: "Pack tactics optional",
      notes: "",
      tokenColor: "#7a8a9a",
    },
  },
  {
    id: "bandit",
    category: "skirmisher",
    template: {
      name: "Bandit",
      cr: "1/8",
      ac: 12,
      hp: 11,
      maxHp: 11,
      speed: "30 ft.",
      abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
      attacks: [
        { name: "Scimitar", bonus: 3, damage: "1d6+1" },
        { name: "Light crossbow", bonus: 3, damage: "1d8+1" },
      ],
      traits: "",
      notes: "",
      tokenColor: "#8a6a48",
    },
  },
  {
    id: "goblin",
    category: "skirmisher",
    template: {
      name: "Goblin",
      cr: "1/4",
      ac: 15,
      hp: 7,
      maxHp: 7,
      speed: "30 ft.",
      abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
      attacks: [
        { name: "Scimitar", bonus: 4, damage: "1d6+2" },
        { name: "Shortbow", bonus: 4, damage: "1d6+2" },
      ],
      traits: "Nimble Escape: Disengage or Hide as bonus action",
      notes: "",
      tokenColor: "#5a8a4a",
    },
  },
  {
    id: "wolf",
    category: "skirmisher",
    template: {
      name: "Wolf",
      cr: "1/4",
      ac: 13,
      hp: 11,
      maxHp: 11,
      speed: "40 ft.",
      abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
      attacks: [{ name: "Bite", bonus: 4, damage: "2d4+2", notes: "DC 11 Str or prone" }],
      traits: "Pack Tactics",
      notes: "",
      tokenColor: "#8a8a9a",
    },
  },
  {
    id: "skeleton",
    category: "minion",
    template: {
      name: "Skeleton",
      cr: "1/4",
      ac: 13,
      hp: 13,
      maxHp: 13,
      speed: "30 ft.",
      abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
      attacks: [
        { name: "Shortsword", bonus: 4, damage: "1d6+2" },
        { name: "Shortbow", bonus: 4, damage: "1d6+2" },
      ],
      traits: "Vulnerable bludgeoning; immune poison/exhaustion",
      notes: "",
      tokenColor: "#c8c0b0",
    },
  },
  {
    id: "zombie",
    category: "brute",
    template: {
      name: "Zombie",
      cr: "1/4",
      ac: 8,
      hp: 22,
      maxHp: 22,
      speed: "20 ft.",
      abilities: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
      attacks: [{ name: "Slam", bonus: 3, damage: "1d6+1" }],
      traits: "Undead Fortitude (DC 5+damage Con save)",
      notes: "",
      tokenColor: "#5a6a48",
    },
  },
  {
    id: "orc",
    category: "brute",
    template: {
      name: "Orc",
      cr: "1/2",
      ac: 13,
      hp: 15,
      maxHp: 15,
      speed: "30 ft.",
      abilities: { str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10 },
      attacks: [
        { name: "Greataxe", bonus: 5, damage: "1d12+3" },
        { name: "Javelin", bonus: 5, damage: "1d6+3" },
      ],
      traits: "Aggressive: bonus move toward enemy",
      notes: "",
      tokenColor: "#6a8a48",
    },
  },
  {
    id: "ogre",
    category: "brute",
    template: {
      name: "Ogre",
      cr: "2",
      ac: 11,
      hp: 59,
      maxHp: 59,
      speed: "40 ft.",
      abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
      attacks: [
        { name: "Greatclub", bonus: 6, damage: "2d8+4" },
        { name: "Javelin", bonus: 6, damage: "2d6+4" },
      ],
      traits: "Large",
      notes: "",
      tokenColor: "#8a5a48",
    },
  },
  {
    id: "hobgoblin",
    category: "elite",
    template: {
      name: "Hobgoblin",
      cr: "1/2",
      ac: 18,
      hp: 11,
      maxHp: 11,
      speed: "30 ft.",
      abilities: { str: 13, dex: 12, con: 12, int: 10, wis: 10, cha: 9 },
      attacks: [
        { name: "Longsword", bonus: 3, damage: "1d8+1" },
        { name: "Longbow", bonus: 3, damage: "1d8+1" },
      ],
      traits: "Martial Advantage: +2d6 once/turn with ally adjacent",
      notes: "",
      tokenColor: "#b45448",
    },
  },
  {
    id: "cultist",
    category: "minion",
    template: {
      name: "Cultist",
      cr: "1/8",
      ac: 12,
      hp: 9,
      maxHp: 9,
      speed: "30 ft.",
      abilities: { str: 11, dex: 12, con: 10, int: 10, wis: 11, cha: 10 },
      attacks: [{ name: "Scimitar", bonus: 3, damage: "1d6+1" }],
      traits: "Dark Devotion: advantage vs charm/frighten",
      notes: "",
      tokenColor: "#6a4a8a",
    },
  },
  {
    id: "acolyte",
    category: "npc",
    template: {
      name: "Acolyte",
      cr: "1/4",
      ac: 10,
      hp: 9,
      maxHp: 9,
      speed: "30 ft.",
      abilities: { str: 10, dex: 10, con: 10, int: 10, wis: 14, cha: 11 },
      attacks: [{ name: "Club", bonus: 2, damage: "1d4" }],
      traits: "Spellcasting (Wis): Sacred Flame, Bless, Cure Wounds, Sanctuary",
      notes: "Friendly or hostile NPC",
      tokenColor: "#8a9aad",
    },
  },
  {
    id: "spy",
    category: "skirmisher",
    template: {
      name: "Spy",
      cr: "1",
      ac: 12,
      hp: 27,
      maxHp: 27,
      speed: "30 ft.",
      abilities: { str: 10, dex: 15, con: 10, int: 12, wis: 14, cha: 16 },
      attacks: [
        { name: "Shortsword", bonus: 4, damage: "1d6+2" },
        { name: "Hand crossbow", bonus: 4, damage: "1d6+2" },
      ],
      traits: "Cunning Action; Sneak Attack 2d6",
      notes: "",
      tokenColor: "#4a5a6a",
    },
  },
  {
    id: "veteran",
    category: "elite",
    template: {
      name: "Veteran",
      cr: "3",
      ac: 17,
      hp: 58,
      maxHp: 58,
      speed: "30 ft.",
      abilities: { str: 16, dex: 13, con: 14, int: 10, wis: 11, cha: 10 },
      attacks: [
        { name: "Longsword", bonus: 5, damage: "1d8+3" },
        { name: "Shortsword", bonus: 5, damage: "1d6+3" },
        { name: "Heavy crossbow", bonus: 3, damage: "1d10+1" },
      ],
      traits: "Multiattack: two longsword",
      notes: "",
      tokenColor: "#6a7a8a",
    },
  },
  {
    id: "mage",
    category: "elite",
    template: {
      name: "Mage",
      cr: "6",
      ac: 12,
      hp: 40,
      maxHp: 40,
      speed: "30 ft.",
      abilities: { str: 9, dex: 14, con: 11, int: 17, wis: 12, cha: 11 },
      attacks: [{ name: "Dagger", bonus: 5, damage: "1d4+2" }],
      traits: "Spellcasting (Int): Fire Bolt, Mage Armor, Fireball, Counterspell, Fly…",
      notes: "",
      tokenColor: "#5a7aaa",
    },
  },
  {
    id: "knight",
    category: "elite",
    template: {
      name: "Knight",
      cr: "3",
      ac: 18,
      hp: 52,
      maxHp: 52,
      speed: "30 ft.",
      abilities: { str: 16, dex: 11, con: 14, int: 11, wis: 11, cha: 15 },
      attacks: [
        { name: "Greatsword", bonus: 5, damage: "2d6+3" },
        { name: "Heavy crossbow", bonus: 2, damage: "1d10" },
      ],
      traits: "Brave; Leadership",
      notes: "",
      tokenColor: "#9a8a5a",
    },
  },
  {
    id: "gladiator",
    category: "boss",
    template: {
      name: "Gladiator",
      cr: "5",
      ac: 16,
      hp: 112,
      maxHp: 112,
      speed: "30 ft.",
      abilities: { str: 18, dex: 15, con: 16, int: 10, wis: 12, cha: 15 },
      attacks: [
        { name: "Spear", bonus: 7, damage: "2d6+4" },
        { name: "Shield bash", bonus: 7, damage: "2d4+4", notes: "DC 15 Str or prone" },
      ],
      traits: "Multiattack; Brave; Parry",
      notes: "Arena boss",
      tokenColor: "#b45448",
    },
  },
  {
    id: "basic-npc",
    category: "npc",
    template: {
      name: "Commoner",
      cr: "0",
      ac: 10,
      hp: 4,
      maxHp: 4,
      speed: "30 ft.",
      abilities: { str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10 },
      attacks: [{ name: "Club", bonus: 2, damage: "1d4" }],
      traits: "",
      notes: "Civilian / quest giver",
      tokenColor: "#8a9aad",
    },
  },
  {
    id: "custom",
    category: "npc",
    template: {
      name: "Custom foe",
      cr: "1",
      ac: 13,
      hp: 20,
      maxHp: 20,
      speed: "30 ft.",
      abilities: { str: 14, dex: 12, con: 14, int: 10, wis: 10, cha: 10 },
      attacks: [{ name: "Attack", bonus: 4, damage: "1d8+2" }],
      traits: "",
      notes: "Edit after drop",
      tokenColor: "#b45448",
    },
  },
];

export function makeBestiaryNpc(entry: BestiaryEntry): NpcStatBlock {
  return emptyNpc({ ...entry.template });
}

export const CATEGORY_LABEL: Record<BestiaryEntry["category"], string> = {
  minion: "Minions",
  skirmisher: "Skirmishers",
  brute: "Brutes",
  elite: "Elites",
  boss: "Bosses",
  npc: "NPCs",
};
