/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ApiTableRouteImport } from './routes/api/table'
import { Route as CampaignCampaignIdRouteImport } from './routes/campaign/$campaignId'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibraryCampaignIdRouteImport } from './routes/library/$campaignId'
import { Route as RunCampaignIdRouteImport } from './routes/run/$campaignId'
import { Route as TableCodeRouteImport } from './routes/table/$code'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTableRoute = ApiTableRouteImport.update({
  id: '/api/table',
  path: '/api/table',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCampaignIdRoute = CampaignCampaignIdRouteImport.update({
  id: '/campaign/$campaignId',
  path: '/campaign/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryCampaignIdRoute = LibraryCampaignIdRouteImport.update({
  id: '/library/$campaignId',
  path: '/library/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunCampaignIdRoute = RunCampaignIdRouteImport.update({
  id: '/run/$campaignId',
  path: '/run/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const TableCodeRoute = TableCodeRouteImport.update({
  id: '/table/$code',
  path: '/table/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/table': typeof ApiTableRoute
  '/campaign/$campaignId': typeof CampaignCampaignIdRoute
  '/library/$campaignId': typeof LibraryCampaignIdRoute
  '/run/$campaignId': typeof RunCampaignIdRoute
  '/table/$code': typeof TableCodeRoute
  '/library/': typeof LibraryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/table': typeof ApiTableRoute
  '/campaign/$campaignId': typeof CampaignCampaignIdRoute
  '/library/$campaignId': typeof LibraryCampaignIdRoute
  '/run/$campaignId': typeof RunCampaignIdRoute
  '/table/$code': typeof TableCodeRoute
  '/library': typeof LibraryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/api/rtc': typeof ApiRtcRoute
  '/api/table': typeof ApiTableRoute
  '/campaign/$campaignId': typeof CampaignCampaignIdRoute
  '/library/$campaignId': typeof LibraryCampaignIdRoute
  '/run/$campaignId': typeof RunCampaignIdRoute
  '/table/$code': typeof TableCodeRoute
  '/library/': typeof LibraryIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/api/rtc'
    | '/api/table'
    | '/campaign/$campaignId'
    | '/library/$campaignId'
    | '/run/$campaignId'
    | '/table/$code'
    | '/library/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/api/rtc'
    | '/api/table'
    | '/campaign/$campaignId'
    | '/library/$campaignId'
    | '/run/$campaignId'
    | '/table/$code'
    | '/library'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/login'
    | '/api/rtc'
    | '/api/table'
    | '/campaign/$campaignId'
    | '/library/$campaignId'
    | '/run/$campaignId'
    | '/table/$code'
    | '/library/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiTableRoute: typeof ApiTableRoute
  CampaignCampaignIdRoute: typeof CampaignCampaignIdRoute
  LibraryCampaignIdRoute: typeof LibraryCampaignIdRoute
  RunCampaignIdRoute: typeof RunCampaignIdRoute
  TableCodeRoute: typeof TableCodeRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/table': {
      id: '/api/table'
      path: '/api/table'
      fullPath: '/api/table'
      preLoaderRoute: typeof ApiTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$campaignId': {
      id: '/campaign/$campaignId'
      path: '/campaign/$campaignId'
      fullPath: '/campaign/$campaignId'
      preLoaderRoute: typeof CampaignCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$campaignId': {
      id: '/library/$campaignId'
      path: '/library/$campaignId'
      fullPath: '/library/$campaignId'
      preLoaderRoute: typeof LibraryCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$campaignId': {
      id: '/run/$campaignId'
      path: '/run/$campaignId'
      fullPath: '/run/$campaignId'
      preLoaderRoute: typeof RunCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$code': {
      id: '/table/$code'
      path: '/table/$code'
      fullPath: '/table/$code'
      preLoaderRoute: typeof TableCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiTableRoute: ApiTableRoute,
  CampaignCampaignIdRoute: CampaignCampaignIdRoute,
  LibraryCampaignIdRoute: LibraryCampaignIdRoute,
  RunCampaignIdRoute: RunCampaignIdRoute,
  TableCodeRoute: TableCodeRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
